# Generated by Django 5.2 on 2025-04-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pitchhelpersession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='readmesession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='session',
        ),
        migrations.RemoveField(
            model_name='themeselection',
            name='session',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pitchhelpersession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='readmesession',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='HackathonSession',
        ),
        migrations.DeleteModel(
            name='ThemeSelection',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='PitchHelperSession',
        ),
        migrations.DeleteModel(
            name='ReadmeSession',
        ),
    ]
