export default function ReadmeFile() {
    return (
      <div className="min-h-screen bg-gray-100 p-8">
        <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-md overflow-hidden">
          {/* Header */}
          <div className="bg-gray-800 p-4 flex justify-between items-center">
            <h1 className="text-white text-xl font-mono font-bold">README.md</h1>
            <button className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition-colors">
              Save
            </button>
          </div>
  
          {/* Code Content */}
          <div className="p-6 space-y-6">
            <div className="bg-gray-900 p-4 rounded-md">
              <pre className="text-green-400 font-mono text-sm">
                <code>
                  {`// This file was generated by AI\n`}
                  {`// Please verify critical sections\n`}
                  {`// Last updated: ${new Date().toLocaleDateString()}`}
                </code>
              </pre>
            </div>
  
            {/* Prompt Section */}
            <div className="space-y-4">
              <h2 className="text-2xl font-bold text-gray-800">ENTER THE PROMPT</h2>
              <textarea
                className="w-full p-4 border-2 border-gray-200 rounded-md focus:outline-none focus:border-indigo-500 font-mono"
                rows="4"
                placeholder="Enter your AI command here..."
              />
              <button className="px-6 py-3 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition-colors">
                Generate
              </button>
            </div>
  
            {/* Status Section */}
            <div className="text-center p-4 bg-green-50 rounded-md">
              <p className="text-green-600 font-bold text-lg animate-pulse">
                GOOD!!!
              </p>
            </div>
          </div>
        </div>
      </div>
    )
  }