import AnimatedBackground from "@/components/animation/AnimatedBackground";
import "./globals.css";

export const metadata = {
  title: "Hackinator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <AnimatedBackground branding={false}/>
      </body>
    </html>
  );
}
