import AnimatedBackground from "@/components/animation/AnimatedBackground";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Hackinator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
          <Navbar/>
        <main className="flex-1 flex items-center justify-center">
          {children}
          <AnimatedBackground branding={false}/>
          <ToastContainer />

        </main>
      </body>
    </html>
  );
}
