import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight } from 'lucide-react';

const FileContainer = () => {
  return (
    <div className="w-full max-w-4xl mb-6 mx-auto">
      <div className="relative border-2 border-gray-800 rounded-xl shadow-lg bg-white">
        <div className="flex justify-between items-center px-4 py-3 border-b-2 border-gray-800">
          <span className="font-semibold text-lg text-gray-900">README.md</span>
          <div className="flex space-x-3">
            <button className="text-xs font-semibold text-gray-700 bg-white border-2 border-gray-800 rounded-md px-3 py-1 hover:bg-gray-200 transition ease-in-out transform hover:scale-105">
              Copy
            </button>
            <button className="text-xs font-semibold text-gray-700 bg-white border-2 border-gray-800 rounded-md px-3 py-1 hover:bg-gray-200 transition ease-in-out transform hover:scale-105">
              Download
            </button>
          </div>
        </div>
        <div className="h-80 flex items-center justify-center text-center text-base text-gray-800 font-medium px-8 py-4">
          This is the README file generated by AI on the backend.
        </div>
      </div>
    </div>
  );
};

const PromptInput = () => {
  const [inputValue, setInputValue] = useState('');

  return (
    <motion.div
      className="w-full flex flex-col sm:flex-row justify-center items-center gap-6 mb-6"
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.7, ease: 'easeOut', type: 'spring' }}
    >
      {/* Input box with solid background */}
      <motion.div
        className="w-full sm:w-[500px] flex items-center gap-3 bg-white border border-gray-300 shadow-xl rounded-lg p-4"
        initial={{ scale: 0.95, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        <input
          type="text"
          id="prompt"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          className="w-full outline-none text-sm font-mono text-gray-800 placeholder-gray-500 bg-white"
          placeholder="Enter the prompt..."
        />
      </motion.div>

      {/* Button */}
      <motion.button
        className="flex items-center gap-2 px-5 py-3 bg-white text-black rounded-md font-mono text-lg hover:bg-gray-800 active:scale-95 transition-transform"
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
      >
        Go
        <ArrowRight size={16} />
      </motion.button>
    </motion.div>
  );
};

const ReadmeFile = () => {
  return (
    <div className="relative z-10 flex flex-col items-center justify-center px-4 py-12 ">
      <div className="absolute inset-0 z-0" />

      <div className="relative z-10 w-full max-w-4xl">
        <FileContainer />
        <PromptInput />
      </div>
    </div>
  );
};

export default ReadmeFile;
